<div class="box-wrapper is-hide" id="box-wrapper">
  <div class="box box1" id="box1">1</div>
  <div class="box box2" id="box2">2</div>
  <div class="box box3" id="box3">3</div>
  <div class="box box4" id="box4">4</div>
  <div class="box box5" id="box5">5</div>
  <div class="box box6" id="box6">6</div>
  <div class="box box7" id="box7">7</div>
  <div class="box box8" id="box8">8</div>
  <div class="box box9" id="box9">9</div>
  <div class="box box10" id="box10">10</div>
  <div class="box box11" id="box11">11</div>
  <div class="box box12" id="box12">12</div>
  <div class="box box13" id="box13">13</div>
  <div class="box box14" id="box14">14</div>
  <div class="box box15" id="box15">15</div>
  <div class="box box16" id="box16">16</div>
  <div class="box box17" id="box17">17</div>
  <div class="box box18" id="box18">18</div>
  <div class="box box19" id="box19">19</div>
  <div class="box box20" id="box20">20</div>
  <div class="box box21" id="box21">21</div>
  <div class="box box22" id="box22">22</div>
  <div class="box box23" id="box23">23</div>
  <div class="box box24" id="box24">24</div>
</div>
<p id="targetInfo" class="target-info">見ている要素</p>
<!-- <p id="countInfo" class="count-info">カウンタ:0</p> -->